# Generated by Django 3.2.3 on 2021-06-25 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210624_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookauth',
            options={'verbose_name': 'facebook_auth', 'verbose_name_plural': 'facebook_auths'},
        ),
        migrations.AlterModelOptions(
            name='googleauth',
            options={'verbose_name': 'google_auth', 'verbose_name_plural': 'google_auths'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_auth',
        ),
        migrations.AddField(
            model_name='facebookauth',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_auth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googleauth',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
