# Generated by Django 3.2.3 on 2021-06-25 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210625_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookauth',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebookauth', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googleauth',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='googleauth', to=settings.AUTH_USER_MODEL),
        ),
    ]
